### ISSUE TITLE
Consider reviewing new SeleniumHQ/docker-selenium repo

### ISSUE THREAD

**Issue by mtscout6** [momer/docker-selenium-node#2]
I have been working with the Selenium team to get an official Selenium docker image out there. While it may not be the perfect solution yet, the goal is to get it there as a community. The team would enjoy getting your feedback and potential support as we endeavor to acquire the Docker Official Repo status.

https://github.com/SeleniumHQ/docker-selenium
https://registry.hub.docker.com/repos/selenium/

**Comment by momer** [comment]
@mtscout6 Looks interesting - I wouldn't mind testing it under a few hundred thousand page loads. Have you all tested the nodes under such load? Does it suffer from mass creation of zombie processes?

**Comment by mtscout6** [comment]
I have not yet tested it against massive zombie process creation, do you know of a means to test this? Theoretically though it shouldn't be a problem since we are only running one process `xvfb-run` which is the parent process of the selenium node, which is also the parent of the browser. I would like to add a test though to prove that to be the case.

**Comment by momer** [comment]
@mtscout6 I'd run docker containers of selenium-hub/selenium-node https://github.com/momer/nutch-selenium-grid-plugin crawling, by now, millions of pages. Relevant code at https://github.com/momer/nutch-selenium-grid-plugin/blob/master/nutch/src/plugin/lib-selenium/src/java/org/apache/nutch/protocol/selenium/HttpWebClient.java#L27-L42

Basically, after an hour (without killing firefox somehow) zombies would be growing at a crazy rate.

**Comment by mtscout6** [comment]
Thanks, I'll see what kind of test I can put together!

**Comment by mtscout6** [comment]
Everything looks good. Chrome and Firefox are children of xvfb-run which is the root process. 

This is the `pstree` output of the chrome node while a test is running:

```
➜  docker-selenium git:(master) ✗ docker exec agitated_pike pstree
entry_point.sh---xvfb-run-+-Xvfb---8*[{Xvfb}]
                          `-java-+-chromedriver-2.-+-chrome-+-2*[cat]
                                 |                 |        |-chrome-+-chrome---8*[{chrome}]
                                 |                 |        |        |-chrome---11*[{chrome}]
                                 |                 |        |        `-nacl_helper
                                 |                 |        |-chrome---10*[{chrome}]
                                 |                 |        `-32*[{chrome}]
                                 |                 `-4*[{chromedriver-2.}]
                                 `-30*[{java}]
```

This is the `pstree` output of the firefox node while a test is running:

```
➜  docker-selenium git:(master) ✗ docker exec sick_goldstine pstree
entry_point.sh---xvfb-run-+-Xvfb---8*[{Xvfb}]
                          `-java-+-firefox---44*[{firefox}]
                                 `-29*[{java}]
```

As you can see in both cases the browser is a child process of the selenium java process which is a child of xvfb-run.

Do you see anything else alarming here or is there something else that I should check?

**Comment by momer** [comment]
Looks good to me, I'll have to test it out sometime. Nice work!

**Comment by momer** [comment]
@mtscout6 have you reviewed http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ and do your containers account for this? This is the issue I was thinking about.

**Comment by mtscout6** [comment]
@momer I had a discussion with the core docker team about this, and they are not in favor of phusion. Basically, if you are needing anything at that level then you are not writing idiomatic docker images. The images we have for selenium do not have a zombie process problem and have withstood some rigorous load testing.

**Comment by momer** [comment]
Dope, thought I'd check.

**Comment by mtscout6** [comment]
No worries, good question!
